# Generated by Django 5.1.3 on 2024-11-25 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_vacationrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='approvers',
            field=models.ManyToManyField(related_name='approver_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
