# Generated by Django 5.1.3 on 2024-11-25 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_team_approvers_vacationrequest_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationrequest',
            name='backup_person',
            field=models.ForeignKey(blank=True, help_text='La persona que va a quedar a cargo de tus funciones mientras estás de vacaciones', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='compensatory_days',
            field=models.IntegerField(default=0, help_text='De los días solicitados, cuántos son compensatorios'),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada')], default='PENDING', max_length=10),
        ),
    ]
